var text = [
'****',
'## Headings',
'First-level heading (====)',
'========',
'',
'Second-level heading (----)',
'--------',
'',
'# First-level heading',
'## Second-level heading',
'### Third-level heading',
'#### Fourth-level heading',
'##### Fifth-level heading',
'###### Sixth-level heading',
'',
'## Paragraphs',
'This is a paragraph. It has two sentences.',
'',
'This is another paragraph. It also has two sentences.',
'',
'Line breaks inserted in the text',
'are removed from the final result.',
'To force a line break,  ',
'insert two spaces at the end of the line.',
'',
'### Multiple underscores in words',
'perform_complicated_task',
'do_this_and_do_that_and_another_thing',
'',
'## Lists',
'### Unordered List',
'* An item in a bulleted (unordered) list(*)',
'    * A subitem, indented with 4 spaces',
'        * A sub-subitem, intented with 8 spaces',
'+ Another item in a bulleted list(+)',
'- Another item in a bulleted list(-)',
'',
'### Ordered List',
'1. An item in an enumerated (ordered) list',
'    1. A subitem, indented with 4 spaces',
'        1. A sub-subitem, intented with 8 spaces',
'1. Another item in an enumerated list',
'',
'        var foo = "code in list";',
'        var bar = 1;',
'1. Another item in an enumerated list',
'',
'## Emphasized text',
'- *emphasis* or _emphasis_  (italic)',
'- **strong emphasis** or __strong emphasis__ (bold)',
'- <del>delete</del>',
'- `monospace`',
'',
'## Code',
'    var foo = "Four spaces indent";',
'    var bar = 1;',
'',
'```',
'var foo = "GFM fenced block ```";',
'var bar = 1;',
'```',
'',
'```javascript',
'var foo = "GFM syntax highlight ```javascript";',
'var bar = 1;',
'```',
'',
'## Block quotes',
'> "This entire paragraph of text will be enclosed in an HTML blockquote',
'element. Blockquote elements are reflowable. You may arbitrarily',
'wrap the text to your liking, and it will all be parsed',
'into a single blockquote element."',
'',
'Blockquotes can contain other Markdown elements',
'> ## This is a header.',
'> ',
'> 1.   This is the first list item.',
'> 2.   This is the second list item.',
'> ',
'> Here\'s some example code:',
'> ',
'>     return shell_exec("echo $input | $markdown_script");',
'',
'## Links',
'* [Markdown](http://en.wikipedia.com/wiki/Markdown)',
'* I get 10 times more traffic from [Google][1] than from',
'[Yahoo][2] or [MSN][3].',
'* http://github.com/ (autolink)',
'* <a href="http://flickr.com">Anchor tag</a>',
'',
'[1]: http://google.com/        "Google"',
'[2]: http://search.yahoo.com/  "Yahoo Search"',
'[3]: http://search.msn.com/    "MSN Search"',
'',
'## Horizontal rules',
'***',
'* * *',
'- - -',
'',
'## Table',
'<table class="table table-striped">',
'  <tr>',
'    <th>ID</th><th>Name</th><th>Rank</th>',
'  </tr>',
'  <tr>',
'    <td>1</td><td>Tom Preston-Werner</td><td>Awesome</td>',
'  </tr>',
'  <tr>',
'    <td>2</td><td>Albert Einstein</td><td>Nearly as awesome</td>',
'  </tr>',
'</table>',
'',
'## Images',
'![Frog 1](../1.jpg "Frog 1")',
'![Frog 2][4]',
'',
'[4]: ../2.jpg "Frog 2"',
''
].join('\n');
